// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgMdRCY1pOlX07t8zvdk8XhLanMVte6k',
    appId: '1:224692860088:web:5be7d0df6aabca8ad5304d',
    messagingSenderId: '224692860088',
    projectId: 'chat-app-com-pk',
    authDomain: 'chat-app-com-pk.firebaseapp.com',
    storageBucket: 'chat-app-com-pk.appspot.com',
    measurementId: 'G-XDS35TKYHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdPkbISvISDNrtmwkNi1dbXL2IaK6evI',
    appId: '1:224692860088:android:ceb73de4a41a7b0fd5304d',
    messagingSenderId: '224692860088',
    projectId: 'chat-app-com-pk',
    storageBucket: 'chat-app-com-pk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw37W9AoM3he4vN7xtu6nUP91e2OYlZAA',
    appId: '1:224692860088:ios:b7db255b63665785d5304d',
    messagingSenderId: '224692860088',
    projectId: 'chat-app-com-pk',
    storageBucket: 'chat-app-com-pk.appspot.com',
    iosClientId: '224692860088-rhk91qpcb07u8lu3vlrdgn8rpqkrqvfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );
}
